[package]
name = "easy-ash"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
ash = {version = "0.37", features = ["linked"]}
ash-window = "0.10.0"
raw-window-handle = "0.4"
easy-versions = { git = "https://github.com/ArthurKValladares/Easy-Versions" }